---
manage_repositories_enable_default_repo: true
manage_repositories_enable_custom_repo: true
manage_repositories_main_repo_uri:
  ubuntu: "http://fr.archive.ubuntu.com/ubuntu"
  debian: "http://deb.debian.org/debian"
manage_repositories_custom_repo:
  - name: hashicorp
    uri: "https://apt.releases.hashicorp.com"
    comments: "hashicorp repository"
    types:
      - deb
    suites:
      - "{{ ansible_distribution_release }}"
    components:
      - main
    options:
      Signed-By: "https://apt.releases.hashicorp.com/gpg"
