---
# devel inventory for the ci-factory
plugin: generator
hosts:
  name: "{{ type }}_{{ flavor }}_{{ builder }}_{{ base }}_{{ version }}"
  parents:
    - name: "{{ flavor }}_{{ builder }}_{{ base }}_{{ version }}"
      parents:
        - name: "{{ flavor }}"
    - name: "{{ type }}_{{ builder }}_{{ base }}_{{ version }}"
      parents:
        - name: "{{ type }}_{{ builder }}_{{ base }}"
          parents:
            - name: "{{ type }}_{{ builder }}"
              vars:
                type_builder: "{{ type }}_{{ builder }}"
              parents:
                - name: "{{ type }}"
            - name: "{{ type }}_{{ base }}"
        - name: "{{ builder }}_{{ base }}_{{ version }}"
          parents:
            - name: "{{ builder }}_{{ base }}"
              vars:
                builder_base: "{{ builder }}_{{ base }}"
              parents:
                - name: "{{ builder }}"
                  vars:
                    builder: "{{ builder }}"
            - name: "{{ base }}_{{ version }}"
              vars:
                base_version: "{{ base }}_{{ version }}"
              parents:
                - name: "{{ base }}"
                  vars:
                    base: "{{ base }}"
                - name: "{{ version }}"
                  vars:
                    version: "{{ version }}"
        - name: "{{ type }}_{{ base }}_{{ version }}"
    - name: "{{ type }}_{{ flavor }}_{{ base }}_{{ version }}"
      parents:
        - name: "{{ type }}_{{ flavor }}_{{ base }}"
        - name: "{{ flavor }}_{{ base }}_{{ version }}"
    - name: "{{ type }}_{{ flavor }}_{{ builder }}_{{ base }}"
      parents:
        - name: "{{ flavor }}_{{ builder }}_{{ base }}"
          parents:
            - name: "{{ flavor }}_{{ builder }}"
            - name: "{{ flavor }}_{{ base }}"
        - name: "{{ type }}_{{ flavor }}_{{ builder }}"
          parents:
            - name: "{{ type }}_{{ flavor }}"

layers:
  type:
    - runner
  flavor:
    - terraform
  builder:
    - docker
  base:
    - node
  version:
    - 18
    - 20
