---
# devel inventory for the ci-factory
plugin: generator
hosts:
  name: "{{ flavor }}_{{ builder }}_{{ base }}_{{ version }}"
  parents:
    - name: "variable_inheritance"
      vars:
        flavor: "{{ flavor }}"
        builder: "{{ builder }}"
        base: "{{ base }}"
        version: "{{ version }}"
      parents:
        - name: "{{ flavor }}_{{ builder }}_{{ base }}"
          parents:
            - name: "{{ flavor }}_{{ builder }}"
              parents:
                - name: "{{ flavor }}"
                - name: "{{ builder }}"
            - name: "{{ builder }}_{{ base }}"
              parents:
                - name : "{{ builder }}"
                - name: "{{ base }}"
        - name: "{{ builder }}_{{ base }}_{{ version }}"
          parents:
            - name: "{{ builder }}_{{ base }}"
              parents:
                - name : "{{ builder }}"
                - name: "{{ base }}"
            - name: "{{ base }}_{{ version }}"
              parents:
                - name: "{{ base }}"
                - name: "{{ version}}"

layers:
  flavor:
    - molecule
    - standard
    - terraform
    - renovate
    - certbot
    - ansible
    - packer
  builder:
    - vagrant
    - docker
    - openstack
  base:
    - ubuntu
  version:
    - 1804
    - 2004
    - 2204
