---
name: build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Building
    runs-on: ubuntu-latest
    container:
      image: git.ednz.fr/container-factory/packer-runner:act-latest
      credentials:
        username: ${{ secrets.ACTIONS_USER }}
        password: ${{ secrets.ACTIONS_TOKEN }}
    strategy:
      matrix:
        build_group: [ansible-runners]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "${{ gitea.workspace }}/requirements.txt"

      - name: Generate packer files
        run: source build.sh
        shell: bash
        working-directory: ${{ gitea.workspace }}
        env:
          VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
          VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
          BUILD_GROUP: ${{ matrix.build_group }}

      - name: Display images status
        run: python3 ami-cleanup.py
        shell: bash
        working-directory: ${{ gitea.workspace }}

      - name: Ensure packer files are generated
        run: tree
        shell: bash
        working-directory: ${{ gitea.workspace }}/packer/builds
