---
# requirements file
roles:
  - name: ednz_cloud.manage_repositories
  - name: ednz_cloud.manage_apt_packages
  - name: ednz_cloud.manage_pip_packages
  - name: ednz_cloud.manage_pipx_packages
  - name: ednz_cloud.install_docker
  - name: ednz_cloud.import_vault_root_ca
  - name: ednz_cloud.provision_management_user
