---
- name: "Ansible docker node"
  hosts: "{{ target_host }}"
  gather_facts: true
  become: no
  tasks:
    - name: "Include ednz_cloud.import_vault_root_ca"
      ansible.builtin.include_role:
        name: ednz_cloud.import_vault_root_ca

    - name: "Include ednz_cloud.manage_repositories"
      ansible.builtin.include_role:
        name: ednz_cloud.manage_repositories

    - name: "Include ednz_cloud.manage_apt_packages"
      ansible.builtin.include_role:
        name: ednz_cloud.manage_apt_packages

    - name: "Include ednz_cloud.install_docker"
      ansible.builtin.include_role:
        name: ednz_cloud.install_docker

    - name: "Include ednz_cloud.manage_pip_packages"
      ansible.builtin.include_role:
        name: ednz_cloud.manage_pip_packages

    - name: "Include cleanup tasks"
      ansible.builtin.include_tasks:
        file: "tasks/cleanup_docker.yml"
