---
- name: "Molecule docker ubuntu"
  hosts: "{{ target_host }}"
  gather_facts: true
  become: no
  tasks:
    - name: "Include ednz_cloud.manage_repositories"
      ansible.builtin.include_role:
        name: ednz_cloud.manage_repositories

    - name: "Include ednz_cloud.manage_apt_packages"
      ansible.builtin.include_role:
        name: ednz_cloud.manage_apt_packages

    - name: Comment out imklog in rsyslog.conf
      ansible.builtin.replace:
        path: /etc/rsyslog.conf
        regexp: '^\($ModLoad imklog\)'
        replace: '#$ModLoad imklog'

    - name: "Copy initctl_faker script"
      ansible.builtin.copy:
        src: "{{ inventory_dir }}/group_files/{{ application }}_{{ builder }}_{{ base_name }}/initctl_faker"
        dest: /initctl_faker
        owner: root
        group: root
        mode: '0755'

    - name: "Remove original /sbin/initctl"
      ansible.builtin.file:
        path: /sbin/initctl
        state: absent

    - name: "Symlink initctl_faker"
      ansible.builtin.file:
        src: /initctl_faker
        dest: /sbin/initctl
        owner: root
        group: root
        state: link

    - name: "Generate the en_US.UTF-8 locale"
      ansible.builtin.command: locale-gen en_US.UTF-8

    - name: "Include ednz_cloud.manage_pip_packages"
      ansible.builtin.include_role:
        name: ednz_cloud.manage_pip_packages

    - name: "Ensure /etc/ansible directory exists"
      ansible.builtin.file:
        path: /etc/ansible
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: "Copy ansible hosts file"
      ansible.builtin.copy:
        src: "{{ inventory_dir }}/group_files/{{ application }}_{{ builder }}_{{ base_name }}/hosts"
        dest: /etc/ansible/hosts
        owner: root
        group: root
        mode: '0644'

    - name: "Finds files udev targets"
      ansible.builtin.find:
        paths: "/lib/systemd/system/"
        patterns: "systemd*udev*"
        recurse: yes
        use_regex: yes
      register: _udev_targets

    - name: "Debug"
      ansible.builtin.debug:
        msg: "{{ _udev_targets.files }}"

    - name: "Remove udev targets"
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ _udev_targets.files }}"

    - name: "Remove getty targets"
      file:
        path: /lib/systemd/system/getty.target
        state: absent

    - name: "Include cleanup tasks"
      ansible.builtin.include_tasks:
        file: "tasks/cleanup_{{ ansible_os_family|lower }}_docker.yml"
