---
- name: "Molecule docker debian"
  hosts: "{{ target_host }}"
  gather_facts: true
  become: no
  tasks:
    - name: "Include ednz_cloud.manage_repositories"
      ansible.builtin.include_role:
        name: ednz_cloud.manage_repositories

    - name: "Include ednz_cloud.manage_apt_packages"
      ansible.builtin.include_role:
        name: ednz_cloud.manage_apt_packages

    - name: "Copy initctl_faker script"
      ansible.builtin.copy:
        src: "{{ factory['root_dir'] }}/ansible/inventory/production/group_files/{{ application }}_{{ builder }}_{{ base_name }}/initctl_faker"
        dest: /initctl_faker
        owner: root
        group: root
        mode: '0755'

    - name: "Allow install of system-wide python packages"
      ansible.builtin.file:
        path: /usr/lib/python3.11/EXTERNALLY-MANAGED
        state: absent
      when: ansible_distribution_major_version == "12"

    - name: "Remove original /sbin/initctl"
      ansible.builtin.file:
        path: /sbin/initctl
        state: absent

    - name: "Symlink initctl_faker"
      ansible.builtin.file:
        src: /initctl_faker
        dest: /sbin/initctl
        owner: root
        group: root
        state: link

    - name: "Include ednz_cloud.manage_pip_packages"
      ansible.builtin.include_role:
        name: ednz_cloud.manage_pip_packages

    - name: "Ensure /etc/ansible directory exists"
      ansible.builtin.file:
        path: /etc/ansible
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: "Copy ansible hosts file"
      ansible.builtin.copy:
        src: "{{ inventory_dir }}/group_files/{{ application }}_{{ builder }}_{{ base_name }}/hosts"
        dest: /etc/ansible/hosts
        owner: root
        group: root
        mode: '0644'

    - name: "Remove getty targets"
      file:
        path: /lib/systemd/system/multi-user.target.wants/getty.target
        state: absent

    - name: "Include cleanup tasks"
      ansible.builtin.include_tasks:
        file: "tasks/cleanup_{{ ansible_os_family|lower }}_docker.yml"
