---
- name: "Packer docker node"
  hosts: "{{ target_host }}"
  gather_facts: true
  become: no
  tasks:
    - name: "Include ednxzu.import_vault_root_ca"
      ansible.builtin.include_role:
        name: ednxzu.import_vault_root_ca

    - name: "Include ednxzu.manage_repositories"
      ansible.builtin.include_role:
        name: ednxzu.manage_repositories

    - name: "Include ednxzu.manage_apt_packages"
      ansible.builtin.include_role:
        name: ednxzu.manage_apt_packages

    - name: "Include ednxzu.install_docker"
      ansible.builtin.include_role:
        name: ednxzu.install_docker

    - name: "Include cleanup tasks"
      ansible.builtin.include_tasks:
        file: "tasks/cleanup_docker.yml"
