---
- name: "Openstack AMI"
  hosts: "{{ target_host }}"
  gather_facts: true
  become: true
  remote_user: "{{ ssh_user }}"
  tasks:
    - name: "Include ednxzu.manage_repositories"
      ansible.builtin.include_role:
        name: ednxzu.manage_repositories

    - name: "Include ednxzu.manage_apt_packages"
      ansible.builtin.include_role:
        name: ednxzu.manage_apt_packages

    - name: "Include ednxzu.import_vault_root_ca"
      ansible.builtin.include_role:
        name: ednxzu.import_vault_root_ca
