---
- name: "Standard ami debian"
  hosts: "{{ target_host }}"
  gather_facts: true
  become: true
  remote_user: "{{ ssh_user }}"
  tasks:
    - name: "Include ednz_cloud.import_vault_root_ca"
      ansible.builtin.include_role:
        name: ednz_cloud.import_vault_root_ca

    - name: "Include ednz_cloud.manage_repositories"
      ansible.builtin.include_role:
        name: ednz_cloud.manage_repositories

    - name: "Include ednz_cloud.manage_apt_packages"
      ansible.builtin.include_role:
        name: ednz_cloud.manage_apt_packages
