---
- name: Generate templates
  hosts: "{{ build_group }}"
  become: no
  vars:
    target_build_name: "{{ flavor }}_{{ builder }}_{{ base }}_{{ version }}"
  tasks:
    - name: "Gather facts"
      ansible.builtin.setup:
      delegate_to: localhost
      run_once: true

    - name: "Create /etc/openstack directory"
      ansible.builtin.file:
        path: "/etc/openstack"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true

    - name: "Copy the clouds.yaml config file to /etc/openstack"
      ansible.builtin.copy:
        src: "{{ factory['root_dir'] }}/credentials/clouds.yaml"
        dest: /etc/openstack/clouds.yaml
        mode: '0644'
      delegate_to: localhost
      become: true
      run_once: true

    - name: "Debug"
      ansible.builtin.debug:
        msg: |
          {{ {
            "hostname": inventory_hostname,
            "end-of-life": eol_date,
            "build": eol_date > ansible_date_time.iso8601
          } }}


    - name: "Build packer files and directories"
      when: eol_date > ansible_date_time.iso8601
      block:
        - name: "Create build directories in packer/builds"
          ansible.builtin.file:
            path: "{{ factory['root_dir'] }}/packer/builds/{{ target_build_name }}"
            state: directory
            mode: '0755'
          delegate_to: localhost

        - name: "Generate build files for docker images"
          ansible.builtin.template:
            src: "{{ factory['root_dir'] }}/packer/templates/{{ builder }}/{{ builder }}_build.pkr.hcl.j2"
            dest: "{{ factory['root_dir'] }}/packer/builds/{{ target_build_name }}/{{ target_build_name }}.pkr.hcl"
            mode: '0600'
          delegate_to: localhost
