---
- name: Generate templates
  hosts: "{{ build_group }}"
  become: no
  tasks:
    - name: "Create build directories in packer/builds"
      ansible.builtin.file:
        path: "{{ factory['root_dir'] }}/packer/builds/{{ inventory_hostname }}"
        state: directory
        mode: '0755'
      delegate_to: localhost

    - name: "Generate build files for docker images"
      ansible.builtin.template:
        src: "{{ factory['root_dir'] }}/packer/templates/docker/docker_build.pkr.hcl.j2"
        dest: "{{ factory['root_dir'] }}/packer/builds/{{ inventory_hostname }}/{{ inventory_hostname }}.pkr.hcl"
        mode: '0600'
      delegate_to: localhost
