---
- name: test
  hosts: all
  gather_facts: no
  become: no
  tasks:
    - name: "Test inventory names"
      ansible.builtin.debug:
        msg: |
          {{ inventory_hostname }}
          {{ factory['root_dir'] }}
          {{ docker_base_image }}
      delegate_to: localhost
