---
- name: test
  hosts: "{{ target_host }}"
  gather_facts: true
  become: no
  tasks:
    - name: "Include ednxzu.import_vault_root_ca"
      ansible.builtin.include_role:
        name: ednxzu.import_vault_root_ca

    - name: "Include ednxzu.manage_apt_packages"
      ansible.builtin.include_role:
        name: ednxzu.manage_apt_packages

    - name: "Include ednxzu.install_docker"
      ansible.builtin.include_role:
        name: ednxzu.install_docker
