---
# production inventory for the ci-factory
plugin: generator
hosts:
  name: "ansible_{{ builder }}_{{ base }}_{{ version }}"
  parents:
    - name: "ansible"
    - name: "ansible_{{ builder }}_{{ base }}"
    - name: "{{ builder }}_{{ base }}_{{ version }}"
      parents:
        - name: "{{ builder }}_{{ base }}"
          parents:
            - name: "{{ builder }}"
            - name: "{{ base }}"

layers:
  builder:
    - docker
  base:
    - node
  version:
    - 16
    - 18
    - 20
