---
plugin: generator
hosts:
  name: "{{ application }}_{{ version }}_{{ builder }}_{{ base }}"
  parents:
    - name: "{{ application }}_{{ builder }}_{{ base }}"
      parents:
        - name: "{{ application }}_{{ builder }}_{{ base.split('_')[0] }}"
          parents:
            - name: "{{ application }}_{{ builder }}"
              parents:
                - name: "{{ application }}"
    - name: "{{ builder }}_{{ base }}"
      parents:
        - name: "{{ builder }}_{{ base.split('_')[0] }}"
          parents:
            - name: "{{ builder }}"
              vars:
                builder: "{{ builder }}"
    - name: "{{ base }}"
      vars:
        base: "{{ base }}"
      parents:
        - name: "{{ base.split('_')[0] }}"
          vars:
            base_name: "{{ base.split('_')[0] }}"
          parents:
            - name: base
    - name: "{{ application }}_{{ version }}"
      vars:
        version: "{{ version }}"
      parents:
        - name: "{{ application }}"
          vars:
            application: "{{ application }}"

layers:
  application:
    - factory
  version:
    - latest
  base:
    - node_20
  builder:
    - docker
