---
# production inventory for the ci-factory
plugin: generator
hosts:
  name: "{{ flavor }}_{{ builder }}_{{ base }}_{{ version }}"
  parents:
    - name: "{{ flavor }}_{{ builder }}_{{ base }}"
      parents:
        - name: "{{ flavor }}_{{ builder }}"
          parents:
            - name: "{{ flavor }}"
              vars:
                flavor: "{{ flavor }}"
            - name: "{{ builder }}"
              vars:
                builder: "{{ builder }}"
        - name: "{{ builder }}_{{ base }}"
          parents:
            - name : "{{ builder }}"
              vars:
                builder: "{{ builder }}"
            - name: "{{ base }}"
              vars:
                base: "{{ base }}"
    - name: "{{ builder }}_{{ base }}_{{ version }}"
      parents:
        - name: "{{ builder }}_{{ base }}"
          parents:
            - name : "{{ builder }}"
              vars:
                builder: "{{ builder }}"
            - name: "{{ base }}"
              vars:
                base: "{{ base }}"
        - name: "{{ base }}_{{ version }}"
          parents:
            - name: "{{ base }}"
              vars:
                base: "{{ base }}"
            - name: "{{ version}}"
              vars:
                version: "{{ version }}"


layers:
  flavor:
    - certbot
  builder:
    - docker
  base:
    - node
  version:
    - 18
    - 20
