---
# production inventory for the ci-factory
plugin: generator
hosts:
  name: "{{ flavor }}-{{ builder }}-{{ base }}-{{ version }}.{{ build_domain }}"
  parents:
    - name: "{{ flavor }}_{{ builder }}_{{ base }}"
      vars:
        flavor: "{{ flavor }}"
        builder: "{{ builder }}"
        base: "{{ base }}"
        build_domain: "{{ build_domain }}"
      parents:
        - name: "{{ flavor }}_{{ builder }}"
          parents:
            - name: "{{ flavor }}"
    - name: "{{ builder }}_{{ base }}_{{ version }}"
      vars:
        version: "{{ version }}"
      parents:
        - name: "{{ builder }}_{{ base }}"
          parents:
            - name: "{{ builder }}"
            - name: "{{ base }}"

layers:
  build_domain:
    - gre1.ednz.fr
  flavor:
    - standard
  builder:
    - ami
  base:
    - debian
  version:
    - 11
    - 12
