---
# production inventory for the ci-factory
plugin: generator
hosts:
  name: "{{ flavor }}_{{ builder }}_{{ base }}_{{ version }}"
  parents:
    - name: "{{ flavor }}_{{ builder }}_{{ base }}"
      parents:
        - name: "{{ flavor }}_{{ builder }}"
          parents:
            - name: "{{ flavor }}"
              vars:
                flavor: "{{ flavor }}"
            - name: "{{ builder }}"
              vars:
                builder: "{{ builder }}"
        - name: "{{ builder }}_{{ base }}"
          parents:
            - name : "{{ builder }}"
              vars:
                builder: "{{ builder }}"
            - name: "{{ base }}"
              vars:
                base: "{{ base }}"
              parents:
                - name: "base"
    - name: "{{ builder }}_{{ base }}_{{ version }}"
      parents:
        - name: "{{ builder }}_{{ base }}"
          parents:
            - name : "{{ builder }}"
              vars:
                builder: "{{ builder }}"
            - name: "{{ base }}"
              vars:
                base: "{{ base }}"
              parents:
                - name: "base"
        - name: "{{ base }}_{{ version }}"
          parents:
            - name: "{{ base }}"
              vars:
                base: "{{ base }}"
              parents:
                - name: "base"
            - name: "{{ version}}"
              vars:
                version: "{{ version }}"
              parents:
                - name: "version"
    - name: "{{ build_domain }}"
      vars:
        build_domain: "{{ build_domain }}"

layers:
  build_domain:
    - gre1.ednz.fr
  flavor:
    - standard
  builder:
    - ami
  base:
    - debian
  version:
    - 11
    - 12
