---
# production inventory for the ci-factory
plugin: generator
hosts:
  name: "renovate_{{ builder }}_{{ base }}"
  parents:
    - name: "{{ builder }}_{{ base }}"
      parents:
        - name: "{{ builder }}"
        - name: "{{ base }}"

layers:
  builder:
    - docker
  base:
    - node18
    - node20
