---
# production inventory for the ci-factory
plugin: generator
hosts:
  name: "{{ type }}_{{ builder }}_{{ base }}_{{ version }}"
  parents:
    - name: "{{ builder }}_{{ base }}_{{ version }}"
      parents:
        - name: "{{ builder }}_{{ base }}"
          parents:
            - name: "{{ builder }}"
            - name: "{{ base }}"

layers:
  type:
    - standard
    - renovate
    - terraform
  builder:
    - docker
  base:
    - node
  version:
    - 18
    - 20
