---
# production inventory for the ci-factory
plugin: generator
hosts:
  name: "standard_{{ builder }}_{{ base }}_{{ version }}"
  parents:
    - name: "{{ builder }}_{{ base }}_{{ version }}"
      parents:
        - name: "{{ builder }}_{{ base }}"
          parents:
            - name: "{{ builder }}"
            - name: "{{ base }}"
    - name: "standard"

layers:
  builder:
    - docker
  base:
    - node
  version:
    - 16
    - 18
    - 20
