---
# production inventory for the ci-factory
plugin: generator
hosts:
  name: "{{ flavor }}_{{ builder }}_{{ base }}_{{ version }}"
  parents:
    - name: "{{ flavor }}_{{ builder }}_{{ base }}"
      parents:
        - name: "{{ flavor }}_{{ builder }}"
          parents:
            - name: "{{ flavor }}"
    - name: "{{ builder }}_{{ base }}_{{ version }}"
      parents:
        - name: "{{ builder }}_{{ base }}"
          parents:
            - name: "{{ builder }}"
            - name: "{{ base }}"

layers:
  flavor:
    - terraform
  builder:
    - docker
  base:
    - node
  version:
    - 16
    - 18
    - 20
